A collection of modules that are linked together is called Python Library.
It has code bundels that can be used again and again in different programs.
Library is collection of classes, methods, functions etc.
Library could be in any languages.
Open source community contribute sources from many big global companies.
Each library is a contribution of many big gloabal companies.
You can create a unique idea work on it and donate and add your liab to the open source community.

In [1]:
import numpy as np

In [6]:
print(np.__version__)

1.23.5


In [ ]:
np.show_config()

In [16]:
v = np.arange(10) #vector
print(v)
print(type(v))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [12]:
v = np.arange(20,30)
print(v)

[20 21 22 23 24 25 26 27 28 29]


In [17]:
v = np.arange(25)
print(v)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [13]:
v = np.arange(25)
v = v[::-1]
print(v)

[24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1
  0]


In [20]:
v = np.arange(9).reshape(3,3)
print(v)

#2 square backets is two dimensional
#3 is three dimensional

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [23]:
nz = np.nonzero([1,0,0,2,0,0,3,0,0,0,4,0,0,0,0,0,5,0,0,0,0,0,6])
print(nz)

(array([ 0,  3,  6, 10, 16, 22]),)


In [ ]:
#What is the simple definition of matrix?
#matrix, a set of numbers arranged in rows and columns
#so as to form a rectangular array.

In [29]:
v = np.eye(3)
print(v)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
v = np.eye(5)
print(v)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [28]:
v = np.random.random(10)
print(v)

[0.67189475 0.10602248 0.06940678 0.69585373 0.26307812 0.64222237
 0.26232684 0.66503333 0.36772189 0.89444306]


In [31]:
v = np.random.random((1,1))
print(v)

[[0.71353298]]


In [32]:
v = np.random.random((1,1,1))
print(v)

[[[0.4312292]]]


In [33]:
v = np.random.random((2,2))
print(v)

[[0.8154555  0.28263798]
 [0.1376737  0.47670064]]


In [40]:
v = np.random.random((3,3))
print(v)

[[0.21865743 0.79167765 0.35102442]
 [0.14020288 0.35345248 0.31330901]
 [0.29165712 0.96149353 0.55352584]]


In [34]:
v = np.random.random((2,2,2))
print(v)

[[[1.89469688e-01 3.50389782e-04]
  [5.25202216e-01 8.12036404e-01]]

 [[9.09604064e-01 3.64889161e-01]
  [9.53096983e-01 9.46421047e-01]]]


In [41]:
v = np.random.random((3,3,3))
print(v)

[[[0.66299057 0.254141   0.42213329]
  [0.55764865 0.71873173 0.1364434 ]
  [0.61738571 0.72879471 0.99438135]]

 [[0.36686443 0.15141795 0.54546292]
  [0.65649641 0.41049052 0.75165996]
  [0.62872999 0.13768606 0.20331662]]

 [[0.51421918 0.85374224 0.66929076]
  [0.90021932 0.71128158 0.56548189]
  [0.92069453 0.11877056 0.59647583]]]


In [37]:
v = np.random.random((1,2,3))
print(v)

[[[0.94018652 0.64925843 0.98988881]
  [0.60844542 0.64633459 0.50711324]]]


In [38]:
v = np.random.random((2,3,4))
print(v)

[[[0.06942273 0.48335152 0.35978833 0.92730437]
  [0.82442501 0.49367897 0.75378317 0.18029045]
  [0.91787246 0.75982873 0.14412178 0.92590517]]

 [[0.26738849 0.29826582 0.59953532 0.61260276]
  [0.89292551 0.96701978 0.70208086 0.2473625 ]
  [0.77036923 0.07175118 0.23677625 0.47644928]]]


In [39]:
v = np.random.random((3,4,5))
print(v)

[[[0.05436044 0.97802885 0.08194466 0.94447572 0.94690883]
  [0.16193993 0.57118875 0.2755011  0.08109438 0.56420095]
  [0.43535612 0.42341949 0.72241194 0.31499539 0.60917922]
  [0.16433685 0.41272094 0.06120292 0.36894687 0.68609904]]

 [[0.2654176  0.35802538 0.49255638 0.88254869 0.72485461]
  [0.01000009 0.01012111 0.42683368 0.44007376 0.41067991]
  [0.35824166 0.06110762 0.79287561 0.8398629  0.20531978]
  [0.75447095 0.6360987  0.21282403 0.59816153 0.06137083]]

 [[0.87238607 0.88492792 0.36613135 0.70223056 0.19783249]
  [0.06465284 0.22612864 0.78685917 0.56236059 0.87850748]
  [0.0618921  0.71214348 0.62317163 0.44474584 0.7932208 ]
  [0.99707168 0.01939711 0.36565934 0.81282289 0.91541829]]]


In [42]:
v = np.random.random((10,10))
v_max, v_min = v.max(), v.min()
print(v_max, v_min)

0.9945827560765823 0.008639414251881528


In [43]:
v = np.random.random((10,10))
v_max, v_min = v.max(), v.min()
print(v_max, v_min)

# same function gives different random values

0.9920781348306401 0.018086068894637153


In [47]:
v = np.random.random(30)
v_mean = v.mean()
print(v_mean)

0.6763843729988906


In [60]:
v = np.zeros((10,10))
print(v)
print(" ")
v[1:-1, 1:-1] = 1
print(v)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
 
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [65]:
#create a 5x5 matrix of 1
#and change inner value to 3
v = np.ones((5,5))
v[1:-1, 1:-1] = 3
print(v)

[[1. 1. 1. 1. 1.]
 [1. 3. 3. 3. 1.]
 [1. 3. 3. 3. 1.]
 [1. 3. 3. 3. 1.]
 [1. 1. 1. 1. 1.]]


In [67]:
v = np.ones((5,5))
print(v)
print(" ")
v = np.pad(v, pad_width=1, mode='constant', constant_values=3)
print(v)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
 
[[3. 3. 3. 3. 3. 3. 3.]
 [3. 1. 1. 1. 1. 1. 3.]
 [3. 1. 1. 1. 1. 1. 3.]
 [3. 1. 1. 1. 1. 1. 3.]
 [3. 1. 1. 1. 1. 1. 3.]
 [3. 1. 1. 1. 1. 1. 3.]
 [3. 3. 3. 3. 3. 3. 3.]]


In [70]:
v = np.ones((6,6))
print(v)
print(" ")
v = np.pad(v, pad_width=2, mode='constant', constant_values=0)
print(v)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
 
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [71]:
np.nan

nan

In [75]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)
3*0.1

nan
False
False
nan
False


0.30000000000000004

In [ ]:
print(np.nan + np.nan)
print(np.nan == np.nan)
print(np.nan != np.nan)
print(np.nan >= np.nan)
print(np.nan <= 0)
print(np.nan >= 0)
print(np.nan == 0)
print(np.nan % np.nan)
print(np.nan * 1)
print(np.nan / 1)
print(np.nan * 0)


In [90]:
v = np.diag([1,2,3,4,5])
print(v)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [96]:
#Create a 5x5 matrix with values 1,2,3,4
#just below the diagonal

#comparison
v = np.zeros((5,5))
print(v)
print(" ")
z =np.diag(1+np.arange(4), k = -1)
print(z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
 
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
