In [153]:
import pandas as pd      # 1. import library
import numpy as np


In [154]:
df = pd.read_excel('/content/Data3 (1).xlsx')   # 2. import dataset
df

Country   Age   Salary Most_Freq Constant Purchased
0   France  44.0  72000.0      Pune    India        No
1    Spain  27.0  48000.0      Pune    India       Yes
2  Germany  30.0  54000.0    Mumbai    India        No
3    Spain  38.0  61000.0      Pune    India        No
4  Germany  40.0      NaN      Pune    India       Yes
5   France  35.0  58000.0    Nagpur    India       Yes
6    Spain   NaN  52000.0      Pune    India        No
7   France  48.0  79000.0       NaN    India       Yes
8  Germany  50.0  83000.0    Mumbai    India        No
9   France  37.0  67000.0      Pune      NaN       Yes

In [ ]:
df.isna()

In [155]:
X = df.iloc[:, 0:5].values        # assign independent column to x

In [156]:
X

array([['France', 44.0, 72000.0, 'Pune', 'India'],
       ['Spain', 27.0, 48000.0, 'Pune', 'India'],
       ['Germany', 30.0, 54000.0, 'Mumbai', 'India'],
       ['Spain', 38.0, 61000.0, 'Pune', 'India'],
       ['Germany', 40.0, nan, 'Pune', 'India'],
       ['France', 35.0, 58000.0, 'Nagpur', 'India'],
       ['Spain', nan, 52000.0, 'Pune', 'India'],
       ['France', 48.0, 79000.0, nan, 'India'],
       ['Germany', 50.0, 83000.0, 'Mumbai', 'India'],
       ['France', 37.0, 67000.0, 'Pune', nan]], dtype=object)

In [158]:
y = df.iloc[:,-1].values    # assign dependent column to y

In [159]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [160]:
from sklearn.impute import SimpleImputer                               # missing values can be numeric or string
# imputer_me = SimpleImputer(missing_values=np.nan, strategy='mean')     # missing values can only be numeric
imputer_md = SimpleImputer(missing_values=np.nan, strategy='median')   # missing values can only be numeric
imputer_fr = SimpleImputer(missing_values=np.nan, strategy='most_frequent') # missing values can be both
imputer_con = SimpleImputer(missing_values=np.nan, strategy='constant', fill_value='India') # missing values can be both


In [164]:
X[:,1:3] = imputer_md.fit_transform(X[:,1:3])
X[:,3:4] = imputer_fr.fit_transform(X[:,3:4])
X[:,4:5] = imputer_con.fit_transform(X[:,4:5])


In [165]:
X

array([['France', 44.0, 72000.0, 'Pune', 'India'],
       ['Spain', 27.0, 48000.0, 'Pune', 'India'],
       ['Germany', 30.0, 54000.0, 'Mumbai', 'India'],
       ['Spain', 38.0, 61000.0, 'Pune', 'India'],
       ['Germany', 40.0, 61000.0, 'Pune', 'India'],
       ['France', 35.0, 58000.0, 'Nagpur', 'India'],
       ['Spain', 38.0, 52000.0, 'Pune', 'India'],
       ['France', 48.0, 79000.0, 'Pune', 'India'],
       ['Germany', 50.0, 83000.0, 'Mumbai', 'India'],
       ['France', 37.0, 67000.0, 'Pune', 'India']], dtype=object)

In [171]:
from matplotlib import transforms
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder  # OneHotEncoder transforms categorical variable as numeric values for machine learning

In [187]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[0,3,4])], remainder = 'passthrough') #0,3,4 had missing values
X = ct.fit_transform(X)

In [175]:
X

array([[1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 40.0, 61000.0],
       [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 38.0, 52000.0],
       [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 37.0, 67000.0]], dtype=object)

In [180]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [181]:
y  # dependent column

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [188]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [189]:
X_train, X_test, y_train, y_test  #output is four arrays which is xtrain, xtest, ytrain and ytest.

(array([[1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 40.0, 61000.0],
        [0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 37.0, 67000.0],
        [1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 27.0, 48000.0],
        [1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 38.0, 52000.0],
        [0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 48.0, 79000.0],
        [1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 38.0, 61000.0],
        [0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 44.0, 72000.0],
        [0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 35.0, 58000.0]],
       dtype=object),
 array([[1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 30.0, 54000.0],
        [1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 50.0, 83000.0]],
       dtype=object),
 array([1, 1, 1, 0, 1, 0, 0, 1]),
 array([0, 0]))

In [192]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()                             # transforms data into machine redable format
X_train[:, 9:] = sc.fit_transform(X_train[:, 9:])
X_test[:, 9:] = sc.fit_transform(X_test[:, 9:])
X_train, X_test

(array([[1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.3779644730092272, 0.0,
         0.2797802353336846, -0.1310806262732691],
        [0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.3779644730092272, 0.0,
         -0.23673712220542542, 0.49810637983842254],
        [1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.3779644730092272, 0.0,
         -1.9584616473357923, -1.4943191395152677],
        [1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.3779644730092272, 0.0,
         -0.06456466969238875, -1.0748611354408066],
        [0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.3779644730092272, 0.0,
         1.657159855437978, 1.7564803920618057],
        [1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.3779644730092272, 0.0,
         -0.06456466969238875, -0.1310806262732691],
        [0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.3779644730092272, 0.0,
         0.9684700453858314, 1.022428884931499],
        [0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, -2.6457513110645903, 0.0,
         -0.5810820272314988, -0.44567412932911