In [24]:
#1. import libraries
import pandas as pd
import numpy as np

In [25]:
#2. import dataset
data = pd.read_excel('/content/Data3 (1).xlsx')
data

Country   Age   Salary Most_Freq Constant Purchased
0   France  44.0  72000.0      Pune    India        No
1    Spain  27.0  48000.0      Pune    India       Yes
2  Germany  30.0  54000.0    Mumbai    India        No
3    Spain  38.0  61000.0      Pune    India        No
4  Germany  40.0      NaN      Pune    India       Yes
5   France  35.0  58000.0    Nagpur    India       Yes
6    Spain   NaN  52000.0      Pune    India        No
7   France  48.0  79000.0       NaN    India       Yes
8  Germany  50.0  83000.0    Mumbai    India        No
9   France  37.0  67000.0      Pune      NaN       Yes

In [26]:
#3. distinguish between independent (x) and dependent (y)
x = data.iloc[:,0:5].values
x

array([['France', 44.0, 72000.0, 'Pune', 'India'],
       ['Spain', 27.0, 48000.0, 'Pune', 'India'],
       ['Germany', 30.0, 54000.0, 'Mumbai', 'India'],
       ['Spain', 38.0, 61000.0, 'Pune', 'India'],
       ['Germany', 40.0, nan, 'Pune', 'India'],
       ['France', 35.0, 58000.0, 'Nagpur', 'India'],
       ['Spain', nan, 52000.0, 'Pune', 'India'],
       ['France', 48.0, 79000.0, nan, 'India'],
       ['Germany', 50.0, 83000.0, 'Mumbai', 'India'],
       ['France', 37.0, 67000.0, 'Pune', nan]], dtype=object)

In [27]:
y = data.iloc[:,-1].values
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [28]:
#4. there are missing values on age, salary, most_frequent and constant
#   lets replace missing values on age and salary with median and most frequent with mode and country with constant

from sklearn.impute import SimpleImputer
#imputer_mean = SimpleImputer(missing_values=np.nan, strategy = 'mean') # for integers
imputer_meadian = SimpleImputer(missing_values=np.nan, strategy = 'median')  # for integers
imputer_most_frequent = SimpleImputer(missing_values=np.nan, strategy='most_frequent') # for categorical value
imputer_constant = SimpleImputer(missing_values=np.nan, strategy='constant', fill_value='India') # for cat


In [29]:
# use above function in a respectable columns
x[:,1:3] = imputer_meadian.fit_transform(x[:,1:3])  # for age and salary
x[:,3:4] = imputer_most_frequent.fit_transform(x[:,3:4]) # for most_frequent city
x[:,4:5] = imputer_constant.fit_transform(x[:,4:5]) # for constant country India
x

array([['France', 44.0, 72000.0, 'Pune', 'India'],
       ['Spain', 27.0, 48000.0, 'Pune', 'India'],
       ['Germany', 30.0, 54000.0, 'Mumbai', 'India'],
       ['Spain', 38.0, 61000.0, 'Pune', 'India'],
       ['Germany', 40.0, 61000.0, 'Pune', 'India'],
       ['France', 35.0, 58000.0, 'Nagpur', 'India'],
       ['Spain', 38.0, 52000.0, 'Pune', 'India'],
       ['France', 48.0, 79000.0, 'Pune', 'India'],
       ['Germany', 50.0, 83000.0, 'Mumbai', 'India'],
       ['France', 37.0, 67000.0, 'Pune', 'India']], dtype=object)

In [30]:
#5. transform categorical data into numeric
#   coz machine only understands numbers

#   for independent value(x)
from matplotlib import transforms
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [31]:
# for above function input the columns that need to be transformed
# 0,3,4 has categorical variables
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[0,3,4])], remainder = 'passthrough')
x = ct.fit_transform(x)
x

array([[1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 40.0, 61000.0],
       [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 38.0, 52000.0],
       [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 37.0, 67000.0]], dtype=object)

In [35]:
# for dependent value (y)
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [36]:
# ML machine learning from here
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state=0)
x_train, x_test, y_train, y_test

(array([[0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 40.0, 61000.0],
        [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 37.0, 67000.0],
        [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 27.0, 48000.0],
        [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 38.0, 52000.0],
        [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 48.0, 79000.0],
        [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 38.0, 61000.0],
        [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 44.0, 72000.0],
        [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 35.0, 58000.0]], dtype=object),
 array([[0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 30.0, 54000.0],
        [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 50.0, 83000.0]], dtype=object),
 array([1, 1, 1, 0, 1, 0, 0, 1]),
 array([0, 0]))

In [39]:
# breakdown big data column(8 and 9 into small data close to 1 and 0
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:,8:] = sc.fit_transform(x_train[:,8:])
x_test[:,8:] = sc.fit_transform(x_test[:,8:])
x_train, x_test

(array([[0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 40.0, -0.13108062627326897],
        [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 37.0, 0.4981063798384226],
        [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 27.0, -1.4943191395152675],
        [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 38.0, -1.0748611354408064],
        [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 48.0, 1.7564803920618055],
        [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 38.0, -0.13108062627326897],
        [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 44.0, 1.0224288849314989],
        [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 35.0, -0.44567412932911477]],
       dtype=object),
 array([[0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 30.0, -1.0],
        [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 50.0, 1.0]], dtype=object))