**Matrix, a set of numbers arranged in rows and columns so as to form a rectangular array.**

In [2]:
import numpy as np


In [3]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [6]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [7]:
# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [8]:
# Create a checkerboard 8x8 matrix using the tile function

Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [9]:
# Normalize a 5x5 random matrix

Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.78010583 0.21945054 0.02955712 0.86088712 0.53605426]
 [0.70252732 0.26954117 0.06158103 0.26616082 0.71399227]
 [0.87492007 0.55133917 0.63715774 0.         0.63485394]
 [0.91119193 0.98499504 0.9237372  0.1344183  0.09215586]
 [0.59137766 0.07569678 1.         0.74225477 0.56932812]]


In [10]:
# Create a custom dtype that describes a color as four unsigned bytes (RGBA)

color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

<ipython-input-10-5043add1dd64>:3: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


In [11]:
# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [12]:
# Given a 1D array, negate all elements which are between 3 and 8, in place.

Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [13]:
# What is the output of the following script?

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [14]:
# What are the result of the following expressions?

print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-14-ef234b2a6acc>:3: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
<ipython-input-14-ef234b2a6acc>:4: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


In [15]:
# How to round away from zero a float array ?

Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[-3.  8. -3. -8.  3.  7. -1.  1. 10.  8.]


In [16]:
# How to find common values between two arrays?

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 8]


In [17]:
# Is the following expressions true?

np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-17-4cdd710269fc>:3: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [18]:
# How to get the dates of yesterday, today and tomorrow?

yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print('yesterday:',yesterday, 'today:',today, 'tomorrow:',tomorrow)

yesterday: 2023-08-29 today: 2023-08-30 tomorrow: 2023-08-31


In [19]:
# How to get all the dates corresponding to the month of July 2016?

Z = np.arange('2023-07', '2023-08', dtype='datetime64[D]')
print(Z)

['2023-07-01' '2023-07-02' '2023-07-03' '2023-07-04' '2023-07-05'
 '2023-07-06' '2023-07-07' '2023-07-08' '2023-07-09' '2023-07-10'
 '2023-07-11' '2023-07-12' '2023-07-13' '2023-07-14' '2023-07-15'
 '2023-07-16' '2023-07-17' '2023-07-18' '2023-07-19' '2023-07-20'
 '2023-07-21' '2023-07-22' '2023-07-23' '2023-07-24' '2023-07-25'
 '2023-07-26' '2023-07-27' '2023-07-28' '2023-07-29' '2023-07-30'
 '2023-07-31']


In [20]:
# How to compute ((A+B)*(-A/2)) in place (without copy)?

A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [ ]:
# Extract the integer part of a random array using 5 different methods?

Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

In [21]:
# Create a 5x5 matrix with row values ranging from 0 to 4

Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [ ]:
# Consider a generator function that generates 10 integers and use it to build an array

def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

In [ ]:
# Create a vector of size 10 with values ranging from 0 to 1, both excluded

Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

In [ ]:
# Create a random vector of size 10 and sort it

Z = np.random.random(10)
Z.sort()
print(Z)

In [ ]:
# How to sum a small array faster than np.sum?

Z = np.arange(10)
np.add.reduce(Z)

In [ ]:
# Consider two random array A and B, check if they are equal?

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

print(A, B)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

In [ ]:
# Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates?

Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

In [ ]:
# Create random vector of size 10 and replace the maximum value by 0?

Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

In [ ]:
# Create a structured array with x and y coordinates covering the [0,1]x[0,1] area?

Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

In [ ]:
# Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))?

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

In [ ]:
# Print the minimum and maximum representable value for each numpy scalar type?

for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

In [ ]:
# How to find the closest value (to a given scalar) in a vector?

Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

In [ ]:
# How to convert a float (32 bits) array into an integer (32 bits) in place?

Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)
print(Z)

In [ ]:
# What is the equivalent of enumerate for numpy arrays?

Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

In [ ]:
# How to sort an array by the nth column?

Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

In [ ]:
# Find the nearest value from a given value in an array?

Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

**Aug 29, 2023**

In [ ]:
# Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

In [23]:
lst1 = {1,2,3,'a','b','c'}
arr1 = np.array(lst1)
print(arr1)
print(type(arr1))

{'b', 2, 3, 1, 'c', 'a'}
<class 'numpy.ndarray'>


In [24]:
tup2 = ('vehicle','car','transport')
arr2 = np.array(tup2)
print(arr2)
print(type(arr2))

['vehicle' 'car' 'transport']
<class 'numpy.ndarray'>


In [25]:
set3 = [0,1,0,1,0,1,0,1]
arr3 = np.array(set3)
print(arr3)
print(type(arr3))


[0 1 0 1 0 1 0 1]
<class 'numpy.ndarray'>


In [26]:
str4 = "man this python bootcamp"
arr4 = np.array(str4)
print(arr4)

man this python bootcamp


In [27]:
arr1d = np.array(['a','b','c','d'])
print(arr1d)
arr1d.ndim


['a' 'b' 'c' 'd']


1

In [33]:
arr2d = np.array([[1,2,3,4,5],[9,8,7,6,5]])
print(arr2d)
arr2d.ndim

[[1 2 3 4 5]
 [9 8 7 6 5]]


2

In [35]:
arr3d = np.array([[['a',1,2],[1,'b',3]],[[1,2,'c'],['a','b','c']]])
print(arr3d)
arr3d.ndim

[[['a' '1' '2']
  ['1' 'b' '3']]

 [['1' '2' 'c']
  ['a' 'b' 'c']]]


3

In [36]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3
